module.exports = (sequelize, DataTypes) => sequelize.define('User', {
  id: {
    type: DataTypes.INTEGER,
    primaryKey: true,
    autoIncrement: true,
  },
  realm: DataTypes.STRING,
  username: DataTypes.STRING,
  password: DataTypes.STRING,
  credentials: DataTypes.STRING,
  challenges: DataTypes.STRING,
  email: DataTypes.STRING,
  emailVerified: DataTypes.BOOLEAN,
  verificationToken: DataTypes.STRING,
  status: DataTypes.STRING,
  created: DataTypes.DATE,
  lastUpdated: DataTypes.DATE,
  idKunde: DataTypes.INTEGER,
  benachrichtigungsfrist1: DataTypes.INTEGER,
  benachrichtigungsfrist2: DataTypes.INTEGER,
  benachrichtigungsfrist3: DataTypes.INTEGER,
  idStellvertreter: DataTypes.INTEGER,
  stellvertreterAktiv: DataTypes.BOOLEAN,
  vorname: DataTypes.STRING,
  nachname: DataTypes.STRING,
  benachrichtigung: DataTypes.BOOLEAN,
}, {
  createdAt: 'created',
  updatedAt: 'lastUpdated',
  paranoid: false,
  timestamps: true,
  freezeTableName: true,
});
